### ISSUE TITLE
Plotting and Saving DAQ Input Data

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#13]
Using the nidaq wrapper function, is there a way to send camera timing output and photodiode output to the DAQ's digital input?  Would I then be able to plot it real time or at least save the data?  I'm having a hard time finding this sort of documentation on PYDAQ in general.

**Comment by triplem0814** [comment]
Essentially, I am wanting to sample the data digitally at some rate.

**Comment by zhuangjun1981** [comment]
OK. These are lot of questions.

1. photodiode signal is in general an analog signal. You may want to connect it to a analog input channel. Or you can pass it through a analog-to-TTL converter then connect it to a digital input channel.

2. the timing data acquisition functionality is not part of this package. We assume most systems neuroscience labs will have some sort of data acquisition system to record timing information.

3. We use a labview software or a python software in our institute to record the timing info. But I am not the author of these code and do not know if they are shared publicly.

4. @derricw is the original author of the pydaq.py. So @derricw, is there a simple way to use pydaq to record timing info through one ni daq device? If so, it will be great if you can show some simple example code.

Thanks

**Comment by zhuangjun1981** [comment]
Or for a simple acquisition task, you can directly use the [PyDAQmx package](https://pythonhosted.org/PyDAQmx/index.html).

**Comment by triplem0814** [comment]
Oh I see.  In that case, we will be using the PyDAQmx package.
