### ISSUE TITLE
Distance from Eyeball to Monitor

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#14]
In MonitorSetup, the variable dis is labelled as the distance from the eyeball to the monitor.  Does this mean the distance to the center of the monitor or the closest point on the monitor?  As a followup, if it is the closest point, do we set the center to that point on the monitor?  And then, what would C2A be if not the width of the monitor divided by 2?  Additionally, in the 2017 paper, you mention that the "monitor covered approximately −10 to 130 degrees in azimuth and −50 to 60 degrees in altitude".  Where do the limits of the mouse's eye lie in this range?  And what point in the field would be 0 degrees azimuth and 0 degrees altitude?

**Comment by zhuangjun1981** [comment]
dis is the shortest distance from eye ball to the monitor. Let's call the point on the monitor that gives the shortest distance "C". This point C does not have to be the center of the monitor. C2A is the distance from this point C to the anterior edge of monitor.  C2T is the distance from this point C to the top edge of the monitor. 0 degree azimuth is the mid-line between two eyes pointing forward and azimuth increases as it goes to the ipsilateral temporal direction. 0 degree altitude is the horizontal line leveled at  the eye ball, up is positive, down is negative. Mouse visual space covers a big range and there are lots of studies about it. You can start with [this one](https://www.ncbi.nlm.nih.gov/pubmed/6776164). But be aware that their coordinate system maybe different from mine.

**Comment by triplem0814** [comment]
Thank you very much.
