### ISSUE TITLE
Conda Create Environment not Working

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#17]
Hi,
I just tried installing this on a new computer, and I ran into an issue that I have not had on my previous 3 installations.  When I type 'conda env create -f environment.yml' in the command prompt, I get the following message:

> Traceback (most recent call last):
>   File "C:\Users\rylab\Anaconda2\Scripts\conda-env-script.py", line 5, in <module>
     from conda_env.cli.main import main
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda_env\cli\main.py", line 39, in 
     <module> from . import main_create
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda_env\cli\main_create.py", line 12, in <module> from conda.cli import install as cli_install
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module> from conda_package_handling.api import InvalidArchiveError
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\conda_package_handling\api.py", line 3, in <module> from libarchive.exception import ArchiveError as _LibarchiveArchiveError
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\libarchive\__init__.py", line 1, in <module>
 from .entry import ArchiveEntry
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\libarchive\entry.py", line 6, in <module>
 from . import ffi
>   File "C:\Users\rylab\Anaconda2\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
>   File "C:\Users\rylab\Anaconda2\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
>   File "C:\Users\rylab\Anaconda2\lib\ctypes\__init__.py", line 366, in __init__
   self._handle = _dlopen(self._name, mode)
> TypeError: expected string or Unicode object, NoneType found

I was wondering how to resolve this. Thank you.

**Comment by zhuangjun1981** [comment]
looks like it has nothing to do with my package. It fails at `from conda_env.cli.main import main`. Can you create any environment?

**Comment by triplem0814** [comment]
I tried creating a test environment but the same error came up.

**Comment by zhuangjun1981** [comment]
Then this is not the problem of the package. You may want to reinstall conda.

**Comment by triplem0814** [comment]
Just a heads up, it seems to be a problem with the new conda version.  I installed an older version of Anaconda with an older conda version, and it worked with no problems.

**Comment by zhuangjun1981** [comment]
Oh, man. Those updates ...
