### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#8]
I am having some trouble with the Getting Started section.  When I try to run the python commands as described, I get the error that no module 'MonitorSetup' exists.  This occurs because I'm not sure when to activate the environment or from which directory to run python.  I would be happy if you could let me know where exactly to run the script.

Thank you.

**Comment by zhuangjun1981** [comment]
Please pull the current master branch (I just updated it). Follow the installation instruction on the front page. If everything is installed correctly, the scripts should be able to run from anywhere by typing the following lines in command window. Let me know if this helps.

windows:
`activate retinotopic_mapping`
`python <script path>`

mac or linux:
`source activate retinotopic_mapping`
`python <script path>`

**Comment by triplem0814** [comment]
Yes, this was helpful. Thank you.
