### ISSUE TITLE
Changing Screen

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#9]
I am currently trying the two monitor setup, and I was trying to change the stimulus display screen.  In psychopy\experiment\components\settings\__init__.py I changed the screen number but the display screen remained the same.  Is there another way to change the screen?

**Comment by zhuangjun1981** [comment]
Try the `display_screen` variable of `DisplayStimulus.DisplaySequence` object.

Let me know if this helps.

**Comment by triplem0814** [comment]
I can't believe I missed that. Thank you so much.
